[package]
name = "web3_proxy_cli"
version = "0.1.0"
edition = "2021"
default-run = "web3_proxy_cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entities = { path = "../entities" }
migration = { path = "../migration" }
web3_proxy = { path = "../web3_proxy" }

influxdb2 = { git = "https://github.com/llamanodes/influxdb2", features = ["rustls"] }
influxdb2-structmap = { git = "https://github.com/llamanodes/influxdb2/"}

anyhow = "1.0.71"
argh = "0.1.10"
chrono = "0.4.26"
env_logger = "0.10.0"
ethers = "2.0.6"
fdlimit = "0.2.1"
futures = "0.3.28"
glob = "0.3.1"
hashbrown = "0.13.2"
log = "0.4.18"
num = "0.4.0"
num-traits = "0.2.15"
pagerduty-rs = "0.1.6"
parking_lot = "0.12.1"
prettytable = "0.10.0"
proctitle = "0.1.1"
rdkafka = { version = "0.31.0" }
reqwest = "0.11.18"
rmp-serde = "1.1.1"
sentry = { version = "0.31.3", default-features = false, features = ["backtrace", "contexts", "panic", "anyhow", "reqwest", "rustls", "log", "sentry-log"] }
serde = "1.0.163"
serde_json = "1.0.96"
tokio = "1.28.2"
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
ulid = "1.0.0"
uuid = "1.3.3"
