[package]
name = "redis-cell-client"
version = "0.2.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.58"
redis = { version = "0.21.5", features = ["aio", "tokio", "tokio-comp"] }
