[workspace]
members = [
  "linkedhashmap",
  "redis-cell-client",
  "web3-backend",
  "web3-proxy",
]

# TODO: enable lto (and maybe other things proven with benchmarks) once rapid development is done
# TODO: we can't do panic = abort because the websockets disconnect by panicking sometimes
[profile.release]
debug = true
#lto = true
