[workspace]
members = [
  "linkedhashmap",
  "web3-proxy",
  "web3-proxy-frontend",
]

# TODO: enable lto (and maybe other things proven with benchmarks) once rapid development is done
# TODO: we can't do panic = abort because the websockets disconnect by panicking sometimes
[profile.release]
debug = true
#lto = true
