[workspace]
members = [
  "deferred-rate-limiter",
  "entities",
  "migration",
  "redis-rate-limiter",
  "thread-fast-rng",
  "web3_proxy",
]

[profile.release]
# `debug = true` so that sentry can give us line numbers
debug = true
# spend longer compiling for a slightly faster binary
codegen-units = 1
