---
# development config
version: "3.4"

services:
  dev-redis:
    build: ./redis-cell-server/
    ports:
      - 127.0.0.1:6379:6379
      # TODO: expose these ports?

  dev-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_web3_proxy
      MYSQL_DATABASE: dev_web3_proxy
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./data/dev_mysql:/var/lib/mysql

  dev-adminer:
    image: adminer
    ports:
      - 8306:8080
    environment:
      ADMINER_DEFAULT_SERVER: dev-db

  dev-eth:
    extends:
      file: docker-compose.common.yml
      service: base
    volumes:
      - ./config/example.toml:/config.toml
    ports:
      - 127.0.0.1:8544:8544
