---
# development config
version: "3.4"

services:
  # manage the databases with a user friendly interface
  # it is slightly dangerous with "drop all" as a single click
  dev-adminer:
    image: adminer
    ports:
      - 18306:8080
    environment:
      ADMINER_DEFAULT_SERVER: dev-db

  # in dev we use mysql, but production will use RDS or similar
  dev-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_web3_proxy
      MYSQL_DATABASE: dev_web3_proxy
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - ./data/dev_mysql:/var/lib/mysql

  # persistent redis for storing user stats
  # TODO: replace this with a real time series database
  dev-predis:
    extends:
      file: docker-compose.common.yml
      service: persistent_redis
    ports:
      - 16379:6379
    volumes:
      - ./data/dev_predis:/data

  # volatile redis for storing rate limits
  dev-vredis:
    extends:
      file: docker-compose.common.yml
      service: volatile_redis
    ports:
      - 16380:6379
  # dev-eth:
  #   extends:
  #     file: docker-compose.common.yml
  #     service: web3-proxy
  #   volumes:
  #     - ./config/example.toml:/config.toml
  #   ports:
  #     - 8544:8544 # proxy (should be behind something handling HTTPS)
  #     - 8543:8543 # prometheus
