---
# development config
version: "3.4"

services:
  # manage the databases with a user friendly interface
  # it is slightly dangerous with "drop all" as a single click
  dev-adminer:
    image: adminer
    ports:
      - 18306:8080
    environment:
      ADMINER_DEFAULT_SERVER: dev-db

  # in dev we use mysql, but production will use RDS or similar
  dev-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_web3_proxy
      MYSQL_DATABASE: dev_web3_proxy
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - ./data/dev_mysql:/var/lib/mysql

  # volatile redis for storing rate limits
  dev-vredis:
    extends:
      file: docker-compose.common.yml
      service: volatile_redis
    ports:
      - 127.0.0.1:16379:6379
