---
# development config
version: "3.4"

services:
  dev-redis:
    build: ./redis-cell-server/

  dev-eth:
    extends:
      file: docker-compose.common.yml
      service: base
    volumes:
      - ./config/example.toml:/config.toml
    ports:
      - 8544:8544

  dev-user-portal:

  dev-db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  dev-adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: dev-db
