---
# development config
version: "3.4"

services:
  dev-redis:
    extends:
      file: docker-compose.common.yml
      service: volatile_redis
    ports:
      - 127.0.0.1:16379:6379

  dev-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev_web3_proxy
      MYSQL_DATABASE: dev_web3_proxy
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - ./data/dev_mysql:/var/lib/mysql

  dev-influxdb:
    image: influxdb:latest
    ports:
      - '127.0.0.1:18086:8086'
    volumes:
      - ./data/dev_influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=dev_web3_proxy

  dev-otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    expose:
      - 4317

  dev-adminer:
    image: adminer
    ports:
      - 18306:8080
    environment:
      ADMINER_DEFAULT_SERVER: dev-db

  dev-eth:
    extends:
      file: docker-compose.common.yml
      service: base
    volumes:
      - ./config/example.toml:/config.toml
    ports:
      - 8544:8544 # proxy (should be behind something handling HTTPS)
      - 8543:8543 # prometheus
