---
# development config
version: "3.4"

services:
  dev-redis:
    build: ./redis-cell-server/

  dev-eth:
    extends:
      file: docker-compose.common.yml
      service: base
    volumes:
      - ./config/example.toml:/config.toml
    ports:
      - 8544:8544
