[package]
name = "deferred-rate-limiter"
version = "0.2.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
edition = "2021"

[dependencies]
redis-rate-limiter = { path = "../redis-rate-limiter" }

ahash = "0.8.0"
anyhow = "1.0.65"
moka = { version = "0.9.4", default-features = false, features = ["future"] }
tokio = "1.21.1"
tracing = "0.1.36"
