[package]
name = "entities"
version = "0.30.0"
edition = "2021"

[lib]
name = "entities"
path = "src/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { git = "https://github.com/llamanodes/ethers-rs/", rev = "eb68f5d60850008cd302762bd3a5a4bdcfecc713", default-features = false }

sea-orm = "0.11.3"
serde = "1.0.164"
ulid = "1.0.0"
uuid = "1.3.4"
