[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # faster linker
    "-C", "link-arg=-fuse-ld=/usr/local/bin/mold",
    # potentially faster. https://github.com/aws/aws-graviton-getting-started/blob/main/rust.md
    "-C", "target-feature=+lse",
    # potentially faster. https://nnethercote.github.io/perf-book/build-configuration.html
    "-C", "target-cpu=native",
    # tokio unstable is needed for tokio-console
    "--cfg", "tokio_unstable",
    # uuid unstable is needed for zerocopy deserialize
    "--cfg", "uuid_unstable",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # faster linker
    "-C", "link-arg=-fuse-ld=/usr/local/bin/mold",
    # potentially faster. https://github.com/aws/aws-graviton-getting-started/blob/main/rust.md
    "-C", "target-feature=+lse",
    # potentially faster. https://nnethercote.github.io/perf-book/build-configuration.html
    "-C", "target-cpu=native",
    # tokio unstable is needed for tokio-console
    "--cfg", "tokio_unstable",
    # uuid unstable is needed for zerocopy deserialize
    "--cfg", "uuid_unstable",
]
