[package]
name = "deduped_broadcast"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
lru = { version = "0.11.0" }
serde = "1"
tokio = { version = "1.32.0", features = ["full"] }
