[shared]
chain_id = 1

[balanced_rpcs]

    [balanced_rpcs.erigon_archive]
    url = "http://127.0.0.1:8549"
    # TODO: double check soft_limit on erigon
    soft_limit = 100_000

    [balanced_rpcs.erigon_archive_ws]
    url = "ws://127.0.0.1:8549"
    # TODO: double check soft_limit on erigon
    soft_limit = 100_000

    [balanced_rpcs.geth]
    url = "http://127.0.0.1:8545"
    soft_limit = 200_000

    [balanced_rpcs.geth_ws]
    url = "ws://127.0.0.1:8546"
    soft_limit = 200_000

[private_rpcs]
