[app]
chain_id = 1

# TODO: how do we find the optimal db_max_connections? too high actually ends up being slower
db_max_connections = 99
db_url = "mysql://MYSQL_USER:MYSQL_PASSWORD@MYSQL_DOMAIN:MYSQL_PORT/MYSQL_DB"

min_sum_soft_limit = 2_000
min_synced_rpcs = 2

# TODO: how do we find the optimal redis_max_connections? too high actually ends up being slower
volatile_redis_max_connections = 300
volatile_redis_url = "redis://REDIS_DOMAIN:REDIS_PORT/"

redirect_public_url = "https://llamanodes.com/public-rpc"
redirect_user_url = "https://llamanodes.com/dashboard/keys?key={{rpc_key_id}}"

sentry_url = "https://SENTRY_KEY_A.ingest.sentry.io/SENTRY_KEY_B"

# 0 = block all public requests
public_max_concurrent_requests = 3
# 0 = block all public requests
public_requests_per_period = 200

# 10GB of cache
response_cache_max_bytes = 10_000_000_000

[app.allowed_origin_requests_per_period]
"https://chainlist.org" = 1_000

[balanced_rpcs]

    [balanced_rpcs.ankr]
    url = "https://rpc.ankr.com/eth"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.cloudflare]
    url = "https://cloudflare-eth.com"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.blastapi]
    url = "https://eth-mainnet.public.blastapi.io"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.mycryptoapi]
    disabled = true
    url = "https://api.mycryptoapi.com/eth"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.runonflux]
    url = "https://ethereumnodelight.app.runonflux.io"
    soft_limit = 1_000
    weight = 1

    [balanced_rpcs.pokt-v1]
    url = "https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79"
    soft_limit = 500
    weight = 1

    [balanced_rpcs.pokt]
    url = "https://eth-rpc.gateway.pokt.network"
    soft_limit = 500
    weight = 1

    [balanced_rpcs.linkpool]
    url = "https://main-rpc.linkpool.io"
    soft_limit = 500
    weight = 2

    # load balanced light nodes are not very reliable
    [balanced_rpcs.linkpool-light]
    disabled = true
    url = "https://main-light.eth.linkpool.io"
    soft_limit = 100
    weight = 3

[private_rpcs]

# these worked well on ETH 1.0, but 2.0 ends up not working as well. we will re-assess as more validators turn on private transactions

    [private_rpcs.eden]
    disabled = true
    url = "https://api.edennetwork.io/v1/"
    soft_limit = 1_805
    weight = 0

    [private_rpcs.eden_beta]
    disabled = true
    url = "https://api.edennetwork.io/v1/beta"
    soft_limit = 5_861
    weight = 0

    [private_rpcs.ethermine]
    disabled = true
    url = "https://rpc.ethermine.org"
    soft_limit = 5_861
    weight = 0

    [private_rpcs.flashbots]
    disabled = true
    url = "https://rpc.flashbots.net/fast"
    soft_limit = 7_074
    weight = 0

    [private_rpcs.securerpc]
    disabled = true
    url = "https://gibson.securerpc.com/v1"
    soft_limit = 4_560
    weight = 0
