[shared]
chain_id = 1
db_url = "mysql://root:dev_web3_proxy@dev-db:3306/dev_web3_proxy"
db_max_connections = 99
min_sum_soft_limit = 2000
min_synced_rpcs = 2
redis_url = "redis://dev-redis:6379/"
redirect_public_url = "https://llamanodes.com/free-rpc-stats"
redirect_user_url = "https://llamanodes.com/user-rpc-stats/{{user_id}}"
public_rate_limit_per_minute = 0
# 1GB of cache
response_cache_max_bytes = 10000000000

[balanced_rpcs]

    [balanced_rpcs.ankr]
    url = "https://rpc.ankr.com/eth"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.cloudflare]
    url = "https://cloudflare-eth.com"
    soft_limit = 1_000
    weight = 0

    [balanced_rpcs.blastapi]
    url = "https://eth-mainnet.public.blastapi.io"
    soft_limit = 1_000
    weight = 0

    #[balanced_rpcs.mycryptoapi]
    #url = "https://api.mycryptoapi.com/eth"
    #soft_limit = 1_000
    #weight = 0

    [balanced_rpcs.runonflux]
    url = "https://ethereumnodelight.app.runonflux.io"
    soft_limit = 1_000
    weight = 1

    [balanced_rpcs.pokt-v1]
    url = "https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79"
    soft_limit = 500
    weight = 1

    [balanced_rpcs.pokt]
    url = "https://eth-rpc.gateway.pokt.network"
    soft_limit = 500
    weight = 1

    [balanced_rpcs.linkpool]
    url = "https://main-rpc.linkpool.io"
    soft_limit = 500
    weight = 2

    # load balanced light nodes are not very reliable
    #[balanced_rpcs.linkpool-light]
    #url = "https://main-light.eth.linkpool.io"
    #soft_limit = 100
    #weight = 3

[private_rpcs]

    [private_rpcs.eden]
    url = "https://api.edennetwork.io/v1/"
    soft_limit = 1_805
    weight = 0

    [private_rpcs.eden_beta]
    url = "https://api.edennetwork.io/v1/beta"
    soft_limit = 5_861
    weight = 0

    [private_rpcs.ethermine]
    url = "https://rpc.ethermine.org"
    soft_limit = 5_861
    weight = 0

    [private_rpcs.flashbots]
    url = "https://rpc.flashbots.net/fast"
    soft_limit = 7074
    weight = 0

    [private_rpcs.securerpc]
    url = "https://gibson.securerpc.com/v1"
    soft_limit = 4560
    weight = 0
