[shared]
chain_id = 1
# in prod, do `rate_limit_redis = "redis://redis:6379/"`

[balanced_rpcs]

    [balanced_rpcs.ankr]
    url = "https://rpc.ankr.com/eth"
    soft_limit = 1_000

    [balanced_rpcs.cloudflare]
    url = "https://cloudflare-eth.com"
    soft_limit = 1_000

    [balanced_rpcs.flashbots]
    url = "https://rpc.flashbots.net"
    soft_limit = 1_000

    #[balanced_rpcs.linkpool-light]
    #url = "https://main-light.eth.linkpool.io"
    #soft_limit = 1_000

    [balanced_rpcs.blastapi]
    url = "https://eth-mainnet.public.blastapi.io"
    soft_limit = 1_000

    #[balanced_rpcs.mycryptoapi]
    #url = "https://api.mycryptoapi.com/eth"
    #soft_limit = 1_000

    [balanced_rpcs.runonflux]
    url = "https://ethereumnodelight.app.runonflux.io"
    soft_limit = 1_000

    [balanced_rpcs.pokt-v1]
    url = "https://eth-mainnet.gateway.pokt.network/v1/5f3453978e354ab992c4da79"
    soft_limit = 1_000

    [balanced_rpcs.pokt]
    url = "https://eth-rpc.gateway.pokt.network"
    soft_limit = 1_000

    [balanced_rpcs.linkpool]
    url = "https://main-rpc.linkpool.io"
    soft_limit = 1_000

[private_rpcs]

    [private_rpcs.eden]
    url = "https://api.edennetwork.io/v1/"
    soft_limit = 1_805

    [private_rpcs.eden_beta]
    url = "https://api.edennetwork.io/v1/beta"
    soft_limit = 5_861

    [private_rpcs.ethermine]
    url = "https://rpc.ethermine.org"
    soft_limit = 5_861

    [private_rpcs.flashbots]
    url = "https://rpc.flashbots.net"
    soft_limit = 7074

    [private_rpcs.securerpc]
    url = "https://gibson.securerpc.com/v1"
    soft_limit = 4560
