[shared]
chain_id = 1
# in prod, do `rate_limit_redis = "redis://redis:6379/"`
rate_limit_redis = "redis://dev-redis:6379/"

[balanced_rpcs]

    [balanced_rpcs.erigon_archive]
    url = "http://10.11.12.16:8549"
    # TODO: double check soft_limit on erigon
    soft_limit = 100_000

    [balanced_rpcs.erigon_archive_ws]
    url = "ws://10.11.12.16:8549"
    # TODO: double check soft_limit on erigon
    soft_limit = 100_000

    [balanced_rpcs.geth]
    url = "http://10.11.12.16:8545"
    soft_limit = 200_000
    hard_limit = 1_000

    [balanced_rpcs.geth_ws]
    url = "ws://10.11.12.16:8546"
    soft_limit = 200_000

[private_rpcs]
