name: Publish multiarch images on ghcr.io
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: alfredcapital
  IMAGE_NAME: web3-proxy

jobs:
  publish:
    name: Build and push web3-proxy multiarch images
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install flake8 and docker-compose
      run: python -m pip install flake8 docker-compose==1.17.1

    - name: Derive image name
      id: image
      run: |
        IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF/refs\/tags\//}"
        echo "NAME=$IMAGE" >> $GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and export
      uses: docker/build-push-action@v3
      with:
        load: true
        push: true
        tags: ${{ steps.image.outputs.NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build arm64 additionaly and push multiarch image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: "${{ steps.image.outputs.NAME }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        # platforms: linux/amd64
